added duration to camera control stick commands osd
DieHertz/betaflight pull request #1
Opened 2017-05-11 00:57 UTC by lithium

I wanted to use this to also control the secondary OSD on the Runcam Swift 2.
You do this by holding the UP button for 2 seconds.

I added a durationUs argument to cameraControlKeyPress, and added a stick command for it (throttle low, pitch high)

2017-05-11 10:07 UTC, DieHertz requested changes
I don't like the name choice for the new parameter, keyDelayMs contains the _duration_ already, besides you're adding msec to usec judging by the name.

2017-05-11 18:42 UTC, lithium commented
@DieHertz what about something like 'holdDurationMs' ?

2017-05-11 20:09 UTC, DieHertz commented
Perfect, sorry, I wanted to give a similar suggestion but my smartphone ran out of juice :-)

2017-05-18 14:55 UTC, DieHertz approved these changes

2017-05-18 14:56 UTC, merged